FROM python:3.8

# install raspbian/docker/numpy dependencies
RUN apt-get -y install libc-dev
RUN apt-get -y install build-essential

RUN pip3 install pipenv

ENV PROJECT_DIR /usr/src/app

WORKDIR ${PROJECT_DIR}

COPY Pipfile .
COPY Pipfile.lock .
COPY . .

RUN pipenv install --deploy --ignore-pipfile

EXPOSE 5000

CMD ["pipenv", "run", "python", "run.py"]