FROM debian:stretch-slim

RUN apt-get update && apt-get -y dist-upgrade
RUN sudo apt-get autoremove python*
RUN sudo apt-get install -y build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libffi-dev
RUN wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
RUN tar xf Python-3.7.0.tar.xz
RUN cd Python-3.7.0
RUN ./configure –prefix=/usr/local/opt/python-3.7.0
RUN make -j 4
RUN sudo make altinstall
RUN sudo ln -s /usr/local/opt/python-3.7.0/bin/pydoc3.7 /usr/bin/pydoc3.7
RUN sudo ln -s /usr/local/opt/python-3.7.0/bin/python3.7 /usr/bin/python3.7
RUN sudo ln -s /usr/local/opt/python-3.7.0/bin/python3.7m /usr/bin/python3.7m
RUN sudo ln -s /usr/local/opt/python-3.7.0/bin/pyvenv-3.7 /usr/bin/pyvenv-3.7
RUN sudo ln -s /usr/local/opt/python-3.7.0/bin/pip3.7 /usr/bin/pip3.7
RUN alias python=’/usr/bin/python3.7′
RUN alias python3=’/usr/bin/python3.7′
RUN ls /usr/bin/python*
RUN cd ..
RUN sudo rm -r Python-3.7.0
RUN rm Python-3.7.0.tar.xz
RUN . ~/.bashrc


# install PIL dependencies
#RUN apt-get update && apt-get install -y \
#        python-dev python-pip python-setuptools \
#        libffi-dev libxml2-dev libxslt1-dev \
#        libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev \
#        liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk

RUN pip3 install pipenv

ENV PROJECT_DIR /usr/src/app

WORKDIR ${PROJECT_DIR}

COPY Pipfile .
COPY Pipfile.lock .
COPY . .

RUN pipenv install --deploy --ignore-pipfile

EXPOSE 5000

CMD ["pipenv", "run", "python", "run.py"]
